function [ imdb, select ] = IMDBAddVOCtrval( imdb, path, task_num, varargin )
% IMDBADDVOCPERSON   Add to imdb the PASCAL VOC dataset, but use tr/val as train, test as val.
%   Input:
%     PATH struct generated by GETPATH() with path.path_OrigNetresponse field adjusted
%     TASK_NUM the path number (see CNN_CUSTOMTRAIN) that this dataset corresponds to
%   Options:
%     See code comments
% 
% Authors: Zhizhong Li
% 
% See the COPYING file.

[ imdb, select_ ] = IMDBAddVOCPerson( imdb, path, task_num, varargin{:}, 'setstrings', {'trainval', 'test'} );

if isfield(select_, 'trainval'), select.train = select_.trainval; end
if isfield(select_, 'test'),     select.val = select_.test;       end

